# Use root/example as user/password credentials
version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: api
    environment:
      - ADMIN_PASS=${ADMIN_PASS}
      - SERVER_IP=${SERVER_IP}
      - PROMETHEUS=http://prometheus:9090
      - OVPN_ADMIN=http://openvpn:9000
      - MONGODB=mongodb://mongo:27017
      - REDIS=redis:6379
    ports:
      - "80:8080"
    volumes:
      - .:/api
    depends_on:
      - mongo
      - redis
    networks:
      - ad-ctf-paas-net

  mongo:
    image: mongo:5.0
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${ADMIN_PASS}
    ports:
      - "27017:27017"
    networks:
      - ad-ctf-paas-net

  redis:
    image: redis:6.2-alpine
    command: redis-server --requirepass ${ADMIN_PASS}
    ports:
      - "6379:6379"
    networks:
      - ad-ctf-paas-net

networks:
  ad-ctf-paas-net:
    external: true
    name: ad-ctf-paas-net